package id.jayaantara.rupabali.view.ui.main

object MainRoute {
    const val HOME = "home"
    const val FAVORITE_ARTWORK = "favorite_artwork"
    const val CHAT_LIST = "chat_list"
    const val CHAT = "chat"
    const val PROFILE = "profile"
    const val EDUCATION = "education"
    const val NEWS_LIST = "list_news"
    const val NEWS_DETAIL = "news_detail"
    const val EVENT_LIST = "list_event"
    const val EVENT_DETAIL = "event_detail"
    const val USER_LIST = "list_user"
    const val FINE_ART_CATEGORY_DETAILS = "fine_art_category_details"
    const val ARTWORK_CATEGORY_DETAILS = "artwork_category_details"
    const val ARTWORK = "artwork"
    const val ARTWORK_DETAIL = "artwork_detail"
    const val ARTWORK_OWNERSHIP_HISTORY = "artwork_ownership_history"
    const val ARTWORK_ACHIEVEMENT_LIST = "artwork_achievement_list"
    const val ARTWORK_ACHIEVEMENT_DETAIL = "artwork_achievement_detail"
    const val ARTWORK_SUBMISSION_LIST = "artwork_submission_list"
    const val ARTWORK_SUBMISSION = "artwork_submission"
    const val MANAGEMENT_ACCOUNT = "management_account"
    const val USER_VERIFICATION = "user_verification"
    const val EDIT_PROFILE = "edit_profile"
    const val CHANGE_PASSWORD = "change_password"
}